### PR TITLE
Enhancement/issue 17 update dependencies

### PR DESCRIPTION
**Pull request by cxoltero**
resolves issue #17

### CODE REVIEW

**Comment by obuckley-kenzan** [comment]
Can one of the admins verify this patch?

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
ok to test

**Comment by thescientist13** [comment]
so this fails when running on NodeJS 4.x.  Likely we need to bump to Node 6.x in order for this to pass, which I think was expected.

I think for the fact that Node 6 just started in Oct. 2016, we should probably consider this a breaking change.

**Comment by thescientist13** [comment]
ok to test

**Pull request merged**
